# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'crawler_llumar.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

"""
이 프로그램은 PyQt5를 이용하여 간단한 GUI를 구현한 웹 크롤러입니다.
다양한 옵션을 선택하여 다른 스크립트를 실행할 수 있습니다.
'What's New', 'Promotion', 'FAQ' 버튼을 통해 해당 스크립트를 실행합니다.
"""
from PyQt5 import QtCore, QtGui, QtWidgets
import subprocess

class UiDialog(object):
    def setup_ui(self, dialog):
        dialog.setObjectName("Dialog")
        dialog.resize(430, 311)
        self.button_box = QtWidgets.QDialogButtonBox(dialog)
        self.button_box.setGeometry(QtCore.QRect(290, 20, 81, 241))
        self.button_box.setOrientation(QtCore.Qt.Vertical)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel | QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("buttonBox")

        self.background_label = QtWidgets.QLabel(dialog)
        self.background_label.setGeometry(QtCore.QRect(0, 0, 431, 311))
        self.background_label.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 rgba(189, 189, 189), stop:1 rgb(234, 236, 234));")
        self.background_label.setText("")
        self.background_label.setObjectName("backgroundLabel")

        self.title_label = QtWidgets.QLabel(dialog)
        self.title_label.setGeometry(QtCore.QRect(30, 30, 171, 41))
        self.title_label.setStyleSheet("font-size: 18px; font-weight: bold; padding: 10px;")
        self.title_label.setObjectName("titleLabel")

        self.radio_button_new = QtWidgets.QRadioButton(dialog)
        self.radio_button_new.setGeometry(QtCore.QRect(30, 90, 211, 31))
        self.radio_button_new.setStyleSheet("background-color: #e0e0e0; border: 1px solid #a0a0a0; border-radius: 5px; padding: 5px 10px; background-color: #d0d0d0;")
        self.radio_button_new.setObjectName("radioButtonNew")

        self.radio_button_promotion = QtWidgets.QRadioButton(dialog)
        self.radio_button_promotion.setGeometry(QtCore.QRect(30, 170, 211, 31))
        self.radio_button_promotion.setStyleSheet("background-color: #e0e0e0; border: 1px solid #a0a0a0; border-radius: 5px; padding: 5px 10px; background-color: #d0d0d0;")
        self.radio_button_promotion.setObjectName("radioButtonPromotion")

        self.radio_button_faq = QtWidgets.QRadioButton(dialog)
        self.radio_button_faq.setGeometry(QtCore.QRect(30, 130, 211, 31))
        self.radio_button_faq.setStyleSheet("background-color: #e0e0e0; border: 1px solid #a0a0a0; border-radius: 5px; padding: 5px 10px; background-color: #d0d0d0;")
        self.radio_button_faq.setObjectName("radioButtonFaq")

        self.background_label.raise_()
        self.button_box.raise_()
        self.radio_button_new.raise_()
        self.title_label.raise_()
        self.radio_button_promotion.raise_()
        self.radio_button_faq.raise_()

        self.retranslate_ui(dialog)
        self.button_box.accepted.connect(self.on_ok_button_clicked)  # OK 버튼에 함수 연결
        self.button_box.rejected.connect(dialog.reject)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(dialog)

        # Connect radio buttons to their event handlers
        self.radio_button_new.toggled.connect(lambda: self.on_radio_button_clicked(self.radio_button_new))
        self.radio_button_promotion.toggled.connect(lambda: self.on_radio_button_clicked(self.radio_button_promotion))
        self.radio_button_faq.toggled.connect(lambda: self.on_radio_button_clicked(self.radio_button_faq))

    def retranslate_ui(self, dialog):
        _translate = QtCore.QCoreApplication.translate
        dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.title_label.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Web Crawler</span></p></body></html>"))
        self.radio_button_new.setText(_translate("Dialog", "What's New"))
        self.radio_button_promotion.setText(_translate("Dialog", "Promotion"))
        self.radio_button_faq.setText(_translate("Dialog", "FAQ"))

    # 토글 누르면
    def on_radio_button_clicked(self, button):
        if button.isChecked():
            print(f'{button.text()} clicked')

    # OK 버튼을 누르면
    def on_ok_button_clicked(self):
        if self.radio_button_new.isChecked():
            print("Executing whatsnew.py...")
            subprocess.run(["python", "whatsnew/whatsnew.py"])  
        elif self.radio_button_promotion.isChecked():
            print("Executing promotion.py...")
            subprocess.run(["python", "promotion/promotion.py"]) 
        elif self.radio_button_faq.isChecked():
            print("Executing faq.py...")
            subprocess.run(["python", "faq/faq.py"])  
        else:
            print("버튼은 클릭되었으나 실행되지 않음")

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dialog = QtWidgets.QDialog()
    ui = UiDialog()
    ui.setup_ui(dialog)
    dialog.show()
    sys.exit(app.exec_())
